In [1]:
import numpy as np

### 创建ndarray

In [2]:
# 创建一维数组
arr = np.array([1,3,5.7,8,0,-12])

In [5]:
print(arr)

[  1.    3.    5.7   8.    0.  -12. ]


In [4]:
type(arr)

numpy.ndarray

In [7]:
# 创建二维数组
arr2 = np.array([[1,2,3],[2,3,4]])
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
arr3 = np.array([1,2,3,4,5],ndmin=2)
arr3

array([[1, 2, 3, 4, 5]])

### NumPy的矢量化

In [10]:
a = [[1,2,3],[5,7,8],[4,5,6]]
b = [[6,2,1],[2,3,1],[4,5,6]]
print(a)
print(b)

[[1, 2, 3], [5, 7, 8], [4, 5, 6]]
[[6, 2, 1], [2, 3, 1], [4, 5, 6]]


In [11]:
c = a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
a[0][0]

1

In [14]:
c = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(3):
    for j in range(3):
        c[i][j] = a[i][j]*b[i][j]
c

[[6, 4, 3], [10, 21, 8], [16, 25, 36]]

In [15]:
a,b

([[1, 2, 3], [5, 7, 8], [4, 5, 6]], [[6, 2, 1], [2, 3, 1], [4, 5, 6]])

In [16]:
a1 = np.array(a)
b1 = np.array(b)

In [17]:
a1

array([[1, 2, 3],
       [5, 7, 8],
       [4, 5, 6]])

In [18]:
b1

array([[6, 2, 1],
       [2, 3, 1],
       [4, 5, 6]])

In [19]:
c = a1*b1
c

array([[ 6,  4,  3],
       [10, 21,  8],
       [16, 25, 36]])

In [20]:
a1+b1

array([[ 7,  4,  4],
       [ 7, 10,  9],
       [ 8, 10, 12]])

In [21]:
a1/b1

array([[0.16666667, 1.        , 3.        ],
       [2.5       , 2.33333333, 8.        ],
       [1.        , 1.        , 1.        ]])

In [22]:
a1**3

array([[  1,   8,  27],
       [125, 343, 512],
       [ 64, 125, 216]], dtype=int32)

### 数据类型

In [23]:
a = np.array([3.14,1,2,3])

In [24]:
a

array([3.14, 1.  , 2.  , 3.  ])

In [25]:
a.dtype

dtype('float64')

In [26]:
b = np.array([3.14,1,2,3],dtype='int32')
b

array([3, 1, 2, 3])

In [27]:
b.dtype

dtype('int32')

In [28]:
b = np.array([3.14,1,2,3],dtype=np.int16)
b

array([3, 1, 2, 3], dtype=int16)

In [29]:
# astype
a

array([3.14, 1.  , 2.  , 3.  ])

In [30]:
a.astype(np.bool)

array([ True,  True,  True,  True])

In [32]:
a.astype('str')

array(['3.14', '1.0', '2.0', '3.0'], dtype='<U32')

### 常用数组

In [33]:
# 全0数组
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.zeros((3,2,4),dtype=np.int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [37]:
# 全1数组
np.ones(3)

array([1., 1., 1.])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((2,3,4),dtype='int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [41]:
# 全为相同值的数组
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [42]:
np.full((2,3),[[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# 单位矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [45]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.eye(5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [47]:
# 对角矩阵
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [48]:
np.diag([1,2,3,4,5],k=1)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

In [50]:
# 设置空值
type(np.nan)

float

In [52]:
# 随机数组
# 创建整数型随机数组
np.random.randint(1,10,(3,6))

array([[7, 9, 9, 3, 1, 8],
       [7, 1, 2, 9, 9, 4],
       [3, 6, 5, 9, 8, 3]])

In [54]:
# 创建标准正态分布随机数组
# 复杂形式
np.random.standard_normal((4,2))

array([[ 0.86677904, -0.33762582],
       [-0.75299217,  0.29055149],
       [ 0.04836077,  0.83755426],
       [-0.78483334, -0.33699508]])

In [55]:
# 简写形式
np.random.randn(4,2)

array([[ 0.34209708,  2.1722872 ],
       [-0.17184493, -1.23625531],
       [-0.29860101,  0.80760515],
       [-0.91699278, -0.75240524]])

In [56]:
# 普通随机数组
np.random.random((2,3))

array([[0.38981121, 0.53988391, 0.26708192],
       [0.29583081, 0.48869494, 0.71417063]])

In [57]:
# 普通正态分布随机数组
np.random.normal(4,2,(5,3))

array([[2.92479352, 2.89865974, 3.53081049],
       [2.56953287, 5.53842677, 4.1212806 ],
       [6.63955271, 2.94084291, 6.52453277],
       [0.60098499, 4.27337577, 6.48269883],
       [6.12316338, 3.99968653, 4.17524433]])

In [59]:
# 随机数种子
np.random.seed(100)

In [66]:
np.random.seed(100)
a = np.random.randn(2,3)
a

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884]])

In [68]:
# 线性序列数组
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [69]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [70]:
np.linspace(1,101,5)

array([  1.,  26.,  51.,  76., 101.])

In [71]:
np.linspace(1,101,5,endpoint=False)

array([ 1., 21., 41., 61., 81.])

In [72]:
np.linspace(1,101,5,endpoint=False,retstep=True)

(array([ 1., 21., 41., 61., 81.]), 20.0)

### 数组属性

In [75]:
np.random.seed(123)
x1 = np.random.randint(10,size=6)   # 一维数组
x2 = np.random.randint(10,size=(3,4))  # 二维数组
x3 = np.random.randint(10,size=(3,4,5))  # 三维数组

In [76]:
# 查看数组形状
x1.shape

(6,)

In [77]:
x2.shape

(3, 4)

In [78]:
x3.shape

(3, 4, 5)

In [79]:
# 查看维度
x1.ndim

1

In [80]:
x2.ndim

2

In [81]:
x3.ndim

3

In [82]:
# 查看元素个数
x1.size

6

In [83]:
x2.size

12

In [84]:
x3.size

60

In [85]:
x1.itemsize

4

In [86]:
x2.itemsize

4

In [87]:
x = np.array([1,2,3,4,5],dtype=np.float64)

In [88]:
x

array([1., 2., 3., 4., 5.])

In [89]:
x.itemsize

8

### 维度变换

In [90]:
a = np.random.randint(1,100,(2,3,4))
a

array([[[99,  4, 12,  4],
        [95,  7, 10, 88],
        [15, 84, 71, 13]],

       [[55, 28, 39, 18],
        [62, 75, 66, 48],
        [17,  6, 87, 47]]])

In [93]:
a.reshape(3,8)

array([[99,  4, 12,  4, 95,  7, 10, 88],
       [15, 84, 71, 13, 55, 28, 39, 18],
       [62, 75, 66, 48, 17,  6, 87, 47]])

In [92]:
a.reshape(3,3) # 不匹配不能实现

ValueError: cannot reshape array of size 24 into shape (3,3)

In [95]:
a.resize(6,4)

In [96]:
a

array([[99,  4, 12,  4],
       [95,  7, 10, 88],
       [15, 84, 71, 13],
       [55, 28, 39, 18],
       [62, 75, 66, 48],
       [17,  6, 87, 47]])

In [97]:
a.swapaxes(1,0)

array([[99, 95, 15, 55, 62, 17],
       [ 4,  7, 84, 28, 75,  6],
       [12, 10, 71, 39, 66, 87],
       [ 4, 88, 13, 18, 48, 47]])

In [98]:
a.flatten()

array([99,  4, 12,  4, 95,  7, 10, 88, 15, 84, 71, 13, 55, 28, 39, 18, 62,
       75, 66, 48, 17,  6, 87, 47])

### 类型变换

In [99]:
a

array([[99,  4, 12,  4],
       [95,  7, 10, 88],
       [15, 84, 71, 13],
       [55, 28, 39, 18],
       [62, 75, 66, 48],
       [17,  6, 87, 47]])

In [101]:
m = a.astype(np.float32)

In [102]:
m

array([[99.,  4., 12.,  4.],
       [95.,  7., 10., 88.],
       [15., 84., 71., 13.],
       [55., 28., 39., 18.],
       [62., 75., 66., 48.],
       [17.,  6., 87., 47.]], dtype=float32)

In [103]:
m.dtype

dtype('float32')

In [104]:
m.tolist()

[[99.0, 4.0, 12.0, 4.0],
 [95.0, 7.0, 10.0, 88.0],
 [15.0, 84.0, 71.0, 13.0],
 [55.0, 28.0, 39.0, 18.0],
 [62.0, 75.0, 66.0, 48.0],
 [17.0, 6.0, 87.0, 47.0]]

In [105]:
type(m.tolist())

list

### 数组的索引和切片

In [122]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr[3]

3

In [109]:
arr[:3]

array([0, 1, 2])

In [110]:
arr[2:7:2]

array([2, 4, 6])

In [123]:
arr[4:7]='888'

In [124]:
arr

array([  0,   1,   2,   3, 888, 888, 888,   7,   8,   9])

In [118]:
lst = arr[4:7]

In [119]:
lst

array([888, 888, 888])

In [121]:
lst[:]=123

#### 多维数组索引

In [125]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
arr2d[0]

array([1, 2, 3])

In [127]:
arr2d[1]

array([4, 5, 6])

In [128]:
arr2d[1][2]

6

In [129]:
arr2d[1,2]

6

In [130]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [132]:
arr3d = np.arange(1,13).reshape((2,2,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [133]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
arr3d[1][0]

array([7, 8, 9])

In [135]:
arr3d[1,0]

array([7, 8, 9])

In [136]:
arr3d[1,0,2]

9

### 整数索引

In [137]:
x = np.array([[1, 2], [3, 4], [5, 6]])

In [138]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
x[np.ix_([0,1,2],[0,1,0])]

array([[1, 2, 1],
       [3, 4, 3],
       [5, 6, 5]])

In [140]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [141]:
x[[[0,0],[3,3]],
 [[0,2],[0,2]]]

array([[ 0,  2],
       [ 9, 11]])

In [148]:
x[[0]]

array([[0, 1, 2]])

In [144]:
x[[0],[0]]

array([0])

In [150]:
x[[[0,0]],
   [[0,2]]]

array([[0, 2]])

In [147]:
x[[3,3],[0,2]]

array([ 9, 11])

In [152]:
x[[[0,0],[3,3]],
  [[0,2],[0,2]]]

array([[ 0,  2],
       [ 9, 11]])

In [153]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [154]:
x[[[1,2],[2,3]],
  [[0,2],[0,2]]]

array([[ 3,  8],
       [ 6, 11]])

### 布尔掩码索引

In [155]:
x = np.arange(12).reshape(4,3)

In [156]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [157]:
x>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [158]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11])

In [161]:
x[(x>5)&(x<9)]

array([6, 7, 8])

In [162]:
x[(x>5)|(x<9)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [163]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [164]:
np.isnan(a)

array([ True, False, False,  True, False, False, False])

In [165]:
a[np.isnan(a)]

array([nan, nan])

In [166]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

### 数组的切片和组合

In [167]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

In [168]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [169]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [170]:
np.hstack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [171]:
np.row_stack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [172]:
np.column_stack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [173]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [174]:
np.concatenate((a,b),axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

### 切分

In [175]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [176]:
for i in np.hsplit(a,2):
    print(i)
    print("*"*20)

[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
********************
[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]]
********************


In [177]:
for i in np.hsplit(a,3):
    print(i)
    print("*"*20)

ValueError: array split does not result in an equal division

In [180]:
for i in np.vsplit(a,3):
    print(i)
    print("*"*20)

[[0 1 2 3 4 5 6 7]]
********************
[[ 8  9 10 11 12 13 14 15]]
********************
[[16 17 18 19 20 21 22 23]]
********************


In [182]:
for i in np.array_split(a,3,axis=1):
    print(i)
    print("*"*20)

[[ 0  1  2]
 [ 8  9 10]
 [16 17 18]]
********************
[[ 3  4  5]
 [11 12 13]
 [19 20 21]]
********************
[[ 6  7]
 [14 15]
 [22 23]]
********************


### 广播

In [183]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [184]:
a+a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [185]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [186]:
b+5

array([5, 6, 7, 8, 9])

In [187]:
c = np.array([[0,1,2]])
c

array([[0, 1, 2]])

In [188]:
a+c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [189]:
d = np.arange(3).reshape(3,1)
d

array([[0],
       [1],
       [2]])

In [190]:
c+d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 算数函数

In [191]:
a = np.arange(9).reshape(3,3)
b = np.array([10,11,12])
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10 11 12]


In [192]:
# 加法
np.add(a,b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [193]:
# 减法
np.subtract(a,b)

array([[-10, -10, -10],
       [ -7,  -7,  -7],
       [ -4,  -4,  -4]])

In [194]:
np.subtract(b,a)

array([[10, 10, 10],
       [ 7,  7,  7],
       [ 4,  4,  4]])

In [195]:
# 位乘法
np.multiply(a,b)

array([[ 0, 11, 24],
       [30, 44, 60],
       [60, 77, 96]])

In [196]:
# 位除法
np.divide(a,b)

array([[0.        , 0.09090909, 0.16666667],
       [0.3       , 0.36363636, 0.41666667],
       [0.6       , 0.63636364, 0.66666667]])

In [197]:
np.divide(b,a)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf, 11.        ,  6.        ],
       [ 3.33333333,  2.75      ,  2.4       ],
       [ 1.66666667,  1.57142857,  1.5       ]])

In [199]:
# 求幂
np.power(b,3)

array([1000, 1331, 1728], dtype=int32)

In [200]:
np.power(3,b)

array([ 59049, 177147, 531441], dtype=int32)

In [203]:
# around
a = np.array([1.0,5.55,123,0.567,12.523])
a

array([  1.   ,   5.55 , 123.   ,   0.567,  12.523])

In [204]:
np.around(a)

array([  1.,   6., 123.,   1.,  13.])

In [205]:
np.around(a,decimals=1)

array([  1. ,   5.6, 123. ,   0.6,  12.5])

In [206]:
np.around(a,decimals=-1)

array([  0.,  10., 120.,   0.,  10.])

In [207]:
np.floor(a)

array([  1.,   5., 123.,   0.,  12.])

In [208]:
np.ceil(a)

array([  1.,   6., 123.,   1.,  13.])

### 字符串函数

In [209]:
x = np.array([['Hello'],['Hi']])
x

array([['Hello'],
       ['Hi']], dtype='<U5')

In [210]:
y = np.array([['abc'],['xyz']])
y

array([['abc'],
       ['xyz']], dtype='<U3')

In [211]:
np.char.add(x,y)

array([['Helloabc'],
       ['Hixyz']], dtype='<U8')

In [212]:
np.char.multiply(x,3)

array([['HelloHelloHello'],
       ['HiHiHi']], dtype='<U15')

In [216]:
np.char.center(x,20,fillchar="*")

array([['*******Hello********'],
       ['*********Hi*********']], dtype='<U20')

### 统计函数

In [218]:
a = np.array([[3,5,7],[8,4,3],[2,4,9]])
a

array([[3, 5, 7],
       [8, 4, 3],
       [2, 4, 9]])

In [219]:
np.amin(a)

2

In [220]:
np.amin(a,axis=0)

array([2, 4, 3])

In [221]:
np.amin(a,axis=1)

array([3, 3, 2])

In [222]:
np.amax(a,axis=0)

array([8, 5, 9])

In [223]:
np.amax(a,axis=1)

array([7, 8, 9])

In [224]:
a

array([[3, 5, 7],
       [8, 4, 3],
       [2, 4, 9]])

In [225]:
np.ptp(a,0)

array([6, 1, 6])

In [226]:
np.ptp(a,1)

array([4, 5, 7])

In [227]:
a1 = np.array([[30,40,70],[80,20,10],[50,90,60]])
a1

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [228]:
np.percentile(a1,50)

50.0

In [229]:
np.percentile(a1,50,axis=0)

array([50., 40., 60.])

In [230]:
np.percentile(a1,25,axis=0)

array([40., 30., 35.])

Q1的位置 = (n+1)*0.25
Q2 = (n+1)*0.5
Q3 =(n+1)*0.75

In [233]:
np.median(a1,axis=1)

array([40., 20., 60.])

In [234]:
a1

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [236]:
a1.mean(axis=0)

array([53.33333333, 50.        , 46.66666667])

In [238]:
np.mean(a1,axis=0)

array([53.33333333, 50.        , 46.66666667])

In [239]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [240]:
np.average(a)

2.5

In [241]:
np.mean(a)

2.5

In [242]:
w = np.array([4,3,2,1])

In [243]:
np.average(a,weights=w)

2.0

In [244]:
np.std(a)

1.118033988749895

In [245]:
np.var(a)

1.25

### 排序

In [247]:
a = np.array([[3,7],[9,1]])
a

array([[3, 7],
       [9, 1]])

In [248]:
np.sort(a)

array([[3, 7],
       [1, 9]])

In [249]:
np.sort(a,axis=0)

array([[3, 1],
       [9, 7]])

In [250]:
x = np.array([3,1,2])
x

array([3, 1, 2])

In [251]:
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [252]:
x[np.argsort(x)]

array([1, 2, 3])

In [253]:
a = [1,5,1,4,3,4,4]
b = [9,4,0,4,0,2,1]

In [254]:
# lexsort
np.lexsort((b,a)) # sort by a,then by b

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

a = [1,1,3,4,4,4,5]
b = [9,0,0,4,2,1,4]
sort by b
(1,0)(1,9)(3,0)(4,1)(4,2)(4,4)(5,4)
a = [1,5,1,4,3,4,4]
b = [9,4,0,4,0,2,1]
2,0,4,6,5,3,1

In [255]:
ind = np.lexsort((b,a))
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [257]:
[(a[i],b[i]) for i  in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

In [258]:
a1 = np.array([[30,40,70],[80,20,10],[50,90,60]])
a1

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [260]:
np.argmax(a1)

7

In [263]:
a1.flatten()

array([30, 40, 70, 80, 20, 10, 50, 90, 60])

In [264]:
np.argmax(a1,axis=0)

array([1, 2, 0], dtype=int64)

In [265]:
a2 = np.array([[30,40,0],[0,20,10],[50,0,60]])
a2

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [267]:
np.nonzero(a2) # axis=0,axis=1

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

In [268]:
a2[np.nonzero(a2)]

array([30, 40, 20, 10, 50, 60])

In [269]:
# np.where
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [270]:
np.where(x>3)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [271]:
x[np.where(x>3)]

array([4, 5, 6, 7, 8])

In [272]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

In [273]:
np.where(a>b,a,b)

array([5, 4, 3, 4, 5])

In [274]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [275]:
condition = np.mod(x,2)==0
condition

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [276]:
np.extract(condition,x)

array([0, 2, 4, 6, 8])

In [277]:
x.T # 转置

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [278]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [279]:
a.T

array([0, 1, 2, 3, 4, 5, 6])

### 唯一化

In [280]:
arr = np.array([1,2,3,4,2,3,4,4,5,1,1])
arr

array([1, 2, 3, 4, 2, 3, 4, 4, 5, 1, 1])

In [281]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [282]:
np.in1d(arr,[0,5,3])

array([False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [283]:
arr2 = np.array([1,2,3,4,5,6,7,8])

In [284]:
# 求交集
np.intersect1d(arr,arr2)

array([1, 2, 3, 4, 5])

In [285]:
# 求并集
np.union1d(arr,arr2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [286]:
# 求差集
np.setdiff1d(arr,arr2)

array([], dtype=int32)

In [287]:
np.setdiff1d(arr2,arr)

array([6, 7, 8])