### 矩阵库

In [3]:
import numpy as np
import numpy.matlib

In [4]:
# 全0的矩阵
m = np.matlib.zeros((2,3))

In [5]:
m

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
type(m)

numpy.matrixlib.defmatrix.matrix

In [7]:
# 全1矩阵
m1 = np.matlib.ones((2,2))
m1

matrix([[1., 1.],
        [1., 1.]])

In [8]:
# 单位矩阵
m2 = np.matlib.eye(n=3,M=4,k=1)
m2

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [9]:
m3 = np.matlib.identity(5,dtype=np.float)
m3

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
# 随机数矩阵
m4 = np.matlib.rand(2,3)
m4
# 矩阵只能是二维的

matrix([[0.57756582, 0.95668548, 0.88913535],
        [0.57351129, 0.03745584, 0.06044221]])

In [13]:
# 转换
m5 = np.matrix('1,2;3,4')
m5

matrix([[1, 2],
        [3, 4]])

In [14]:
arr = np.asarray(m5) # 转换成数组
arr

array([[1, 2],
       [3, 4]])

In [15]:
# 数组转矩阵
m6 = np.mat(arr)
m6

matrix([[1, 2],
        [3, 4]])

### 线性代数

In [16]:
# 点积
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [17]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [18]:
# 向量的点积
np.vdot(a,b)

130

In [19]:
a,b

(array([[1, 2],
        [3, 4]]), array([[11, 12],
        [13, 14]]))

In [20]:
a = np.array([1,2,3,4])
b = np.array([11,12,13,14]).reshape(4,1)
a,b

(array([1, 2, 3, 4]), array([[11],
        [12],
        [13],
        [14]]))

In [21]:
np.vdot(a,b)

130

In [22]:
# 向量内积
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a,b)

2

In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [24]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

In [25]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [27]:
# 矩阵乘积
np.matmul(a,b)  # 对于二维数组，等于矩阵乘法

array([[37, 40],
       [85, 92]])

In [28]:
# 行列式
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [29]:
np.linalg.det(a)

-2.0000000000000004

In [30]:
# 三阶行列式
b = np.array([[6,1,1],[4,-2,5],[2,8,7]])
b

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [ ]:
(6*-2*7+1*5*2+1*4*8)-(1*-2*2+1*4*7+6*5*8)

In [31]:
np.linalg.det(b)

-306.0

In [ ]:
# 线性方程解
x+y+z=6
2y+5z=-4
2x+5y-z=27

In [32]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
B = np.array([6,-4,27])

In [34]:
C = np.linalg.solve(A,B)

In [35]:
np.allclose(np.dot(A,C),B)

True

In [36]:
np.dot(A,C)

array([ 6., -4., 27.])

In [38]:
# 矩阵的逆
x = np.array([[1,2],[3,4]])

In [40]:
y = np.linalg.inv(x)

In [41]:
np.dot(x,y)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])